[workspace]
channels = ["conda-forge"]
name = "nurwa_backend"
platforms = ["win-64"]
version = "0.1.0"

[tasks]

[dependencies]
fastapi = ">=0.136.1,<0.137"
uvicorn = ">=0.46.0,<0.47"
pydantic = ">=2.13.3,<3"
